language: java
jdk:
  - oraclejdk8

script: ./gradlew --stacktrace all -Prelease.attachRemote="https://github.com/innodonni/DonniBot.git"

before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN\n  password x-oauth-basic " > ~/.netrc

branches:
  except:
    - /^v[0-9]/