language: java
jdk:
  - oraclejdk8

script: ./grailsw all -Prelease.attachRemote="https://github.com/innodonni/DonniBot.git"

before_install:
  - echo "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc