language: java
jdk:
  - oraclejdk8

before_script:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN\n  password x-oauth-basic " > ~/.netrc

install: gradle clean --refresh-dependencies

script: gradle --stacktrace all -Prelease.disableRemoteCheck -Prelease.attachRemote="https://github.com/innodonni/DonniBot.git"

branches:
  except:
    - /^v[0-9]/