language: java
jdk:
  - oraclejdk8

before_script:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN\n  password x-oauth-basic " > ~/.netrc

# Use system gradle and don't assemble during install to speed up build
install: gradle clean

script: gradle --stacktrace all

branches:
  except:
    - /^v[0-9]/